Update manage_files.py
Bug fix when right clicking on an empty space while opening Manage Files (this issue already existed in version 3.8.2 and master code):

File "D:\z7b\src\qualcoder\manage_files.py", line 444, in table_menu
    item_text = self.ui.tableWidget.item(row, col).text()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'text'

This was changed from:

row = self.ui.tableWidget.currentRow()
col = self.ui.tableWidget.currentColumn()
item_text = self.ui.tableWidget.item(row, col).text()

to:

row = self.ui.tableWidget.currentRow()
col = self.ui.tableWidget.currentColumn()
cell = self.ui.tableWidget.item(row, col)
if cell is None:
    return
item_text = cell.text()